
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 22 11:52:02 COT 2020
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 31;
  public static final int Coma = 45;
  public static final int Llave_c = 38;
  public static final int Op_booleano = 34;
  public static final int Llave_a = 37;
  public static final int If = 6;
  public static final int Namespace = 24;
  public static final int T_dato = 4;
  public static final int Default = 11;
  public static final int Else = 7;
  public static final int Cout = 27;
  public static final int Break = 10;
  public static final int Corchete_c = 40;
  public static final int Corchete_a = 39;
  public static final int Punto = 44;
  public static final int While = 13;
  public static final int Division = 20;
  public static final int Int = 15;
  public static final int Parentesis_c = 36;
  public static final int Cadena = 5;
  public static final int Parentesis_a = 35;
  public static final int For = 14;
  public static final int Std = 25;
  public static final int P_coma = 42;
  public static final int EOF = 0;
  public static final int Printf = 29;
  public static final int error = 1;
  public static final int Switch = 8;
  public static final int Linea = 2;
  public static final int Op_atribucion = 32;
  public static final int ERROR = 48;
  public static final int Do = 12;
  public static final int Op_logico = 30;
  public static final int Case = 9;
  public static final int Dos_puntos = 43;
  public static final int Scanf = 28;
  public static final int Identificador = 46;
  public static final int Using = 23;
  public static final int Cin = 26;
  public static final int Resta = 18;
  public static final int Multiplicacion = 19;
  public static final int Iostream = 22;
  public static final int Op_incremento = 33;
  public static final int Numero = 47;
  public static final int Suma = 17;
  public static final int Include = 21;
  public static final int Main = 41;
  public static final int Igual = 16;
  public static final int Comillas = 3;
}

